// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmq5PDY4dWgcAK_tztb2vd1l8YGAoI1Rk',
    appId: '1:928846656433:web:6e7e5a6245f94db6fe4390',
    messagingSenderId: '928846656433',
    projectId: 'portfolio-d7669',
    authDomain: 'portfolio-d7669.firebaseapp.com',
    databaseURL: 'https://portfolio-d7669-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d7669.firebasestorage.app',
    measurementId: 'G-LHQWS8ZJVJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEyYhMg0ZIxBmOhEqMAKoyvoKGcNa7MCQ',
    appId: '1:928846656433:ios:671eae87148ed48ffe4390',
    messagingSenderId: '928846656433',
    projectId: 'portfolio-d7669',
    databaseURL: 'https://portfolio-d7669-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d7669.firebasestorage.app',
    iosBundleId: 'com.example.yelwinoo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNp7XqRUlk2dUpQjlGmkRO7s_XjirjB0',
    appId: '1:928846656433:android:67a6ed693f1e9ff1fe4390',
    messagingSenderId: '928846656433',
    projectId: 'portfolio-d7669',
    databaseURL: 'https://portfolio-d7669-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d7669.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmq5PDY4dWgcAK_tztb2vd1l8YGAoI1Rk',
    appId: '1:928846656433:web:6e7e5a6245f94db6fe4390',
    messagingSenderId: '928846656433',
    projectId: 'portfolio-d7669',
    authDomain: 'portfolio-d7669.firebaseapp.com',
    databaseURL: 'https://portfolio-d7669-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-d7669.firebasestorage.app',
    measurementId: 'G-LHQWS8ZJVJ',
  );

}